macro(set_strict_compiler_warnings TARGET)
    target_compile_options(${TARGET}
        PRIVATE
        $<$<C_COMPILER_ID:Clang>:-Wcast-align
        -Wcast-qual
        -Wconversion
        -Wexit-time-destructors
        -Wglobal-constructors
        -Wmissing-noreturn
        -Wmissing-prototypes
        -Wno-missing-braces
        -Wold-style-cast
        -Wshadow
        -Wweak-vtables
        -Wall
        -Wextra
        -Wpedantic
        #-Werror
        >
        $<$<C_COMPILER_ID:GNU>:-Waddress
        -Waggregate-return
        -Wformat-nonliteral
        -Wformat-security
        -Wformat
        -Winit-self
        #-Wmissing-declarations
        -Wmissing-include-dirs
        -Wno-multichar
        -Wno-parentheses
        -Wno-type-limits
        -Wno-unused-parameter
        -Wunreachable-code
        -Wwrite-strings
        -Wpointer-arith
        -Wall
        -Wextra
        -Wpedantic
        #-Werror
        >
        $<$<CXX_COMPILER_ID:MSVC>:W4>
        )

endmacro()